export const REQUEST_BANNER_DATA = "REQUEST_BANNER_DATA";
export const RECEIVE_BANNER_DATA = "RECEIVE_BANNER_DATA";
export const REQUEST_CATEGORIES_DATA = "REQUEST_CATEGORIES_DATA";
export const RECEIVE_CATEGORIES_DATA = "RECEIVE_CATEGORIES_DATA";
